name: cltv-env
channels:
  - conda-forge
dependencies:
  # System related
  - python=3.10
  - pip
  - pip:
    - build
    - ipykernel
    - ipywidgets
    - pyyaml
    - types-pyyaml
    # Scipy stack
    - numpy
    - matplotlib
    - pandas
    # GCP
    - google-cloud-aiplatform
    - google-cloud-bigquery
    - google-cloud-secret-manager
    - kfp
    - db-dtypes
    # cltv
    - lifetimes
    - pymc-marketing
    # Others
    - tqdm
    # Testing
    - pytest
    - pytest-cov
    - pytest-mock
    # Formating, linting
    - mypy
    - pylint
    - black
    - isort